### ISSUE TITLE
The behat extension should move to a separate package

### ISSUE THREAD

**Issue by stof** [jcalderonzumba/MinkPhantomJSDriver#37]
As discussed in https://github.com/minkphp/Mink/issues/654, the driver and the behat integration are 2 different things and should live in 2 different packages (the behat integration should depend on both ``behat/mink-extension`` and the driver)

**Comment by jcalderonzumba** [comment]
I completely agree, i have taken the first step by separating the "core" API browser controller into a differente package. Next step will be to break down the extension and the driver.

**Comment by jcalderonzumba** [comment]
@stof So i think this part is done check https://github.com/jcalderonzumba/MinkPhantomJSExtension.
As always all feedback is welcome.

**Comment by stof** [comment]
I'm closing this issue as the extension is now moved

**Comment by stof** [comment]
@jcalderonzumba working on #38 would be great now.

**Comment by jcalderonzumba** [comment]
Yes i'm working on the last comment about the driver implementation regarding tests. Is not an easy fix but will get it working.
