### ISSUE TITLE
Tests of the driver testsuite should not be replaced by modified versions

### ISSUE THREAD

**Issue by stof** [jcalderonzumba/MinkPhantomJSDriver#38]
As discussed in https://github.com/minkphp/Mink/issues/654, this is lying about the fact that the driver implements the API properly. The driver testsuite is precisely here to ensure all drivers behave in a consistent way. So if the implementation does not behave the same, you should see it failing (it is perfectly fine to see failures in your testsuite for now, until you fix the driver. much better than hiding them)

**Comment by jcalderonzumba** [comment]
I will take a look at this, but last time i saw, to make it work i have to do some serious changes in the javascript function evaluation. First setp is to take a look at the separation between driver and extension and then do this fix.

**Comment by stof** [comment]
Well, this is a requirement to make the driver implement the driver API.

**Comment by stof** [comment]
the first step would probably be to run the real tests, allowing to see what the failures are. Then you can make changes 1 by 1 fixing some of these tests. This is what we did on our own drivers when adding all the new driver tests in 1.6+ (and actually, SahiDriver does not yet pass the testsuite, and we have red builds to show it)

**Comment by jcalderonzumba** [comment]
Will definitely do this now that all is splitted.

**Comment by jcalderonzumba** [comment]
Working on it right now.

**Comment by dawehner** [comment]
@jcalderonzumba How its going with that?

**Comment by jcalderonzumba** [comment]
Is a bit complicated, most of the problems are in the part of javascript evaluation or execution, PhantomJS way of handling javascript needs to be double check in order to pass the default tests of MinkDriver.

**Comment by stof** [comment]
@jcalderonzumba for the ``executeScript`` and ``evaluateScript`` tests, you probably need to normalize the input to support all of them. All Mink drivers need to do it (none of the implementation support all syntaxes natively, but they all support different ones natively)

**Comment by jcalderonzumba** [comment]
yes @stof i'm looking into that, there are also another tests that fail not related to javascript like BasicAuth that i'm having troubles with mainly because the way PhantomJS is behaving with BasicAuth even though i'm "reseting" everything internally.
With enough time i'm confident i'll sort it out or get to a point where the number of failures are the minimum i can get.

**Comment by jcalderonzumba** [comment]
update, crazy times at work that i could not take "personal" time from work to the project as when we i was developing it but i'm still trying to get this done in the proper way.

**Comment by dawehner** [comment]
@jcalderonzumba Well, perfect is the enemy of good. Push any kind of start of work onto a local branch, maybe someone will pick it up if they are bored

**Comment by jcalderonzumba** [comment]
@stof @dawehner I started the hard work, i've been busy and slacking. So i removed the self made replacement of test to start fixing step by step. Work is here:

https://github.com/jcalderonzumba/MinkPhantomJSDriver/tree/issue_38

Travis results are here:
https://travis-ci.org/jcalderonzumba/MinkPhantomJSDriver/jobs/96028156

I managed to fix the BestPracticesTest test suite and now will continue to look problem by problem but i saw the following notice not related with the Driver:

```
The Symfony\Component\CssSelector\CssSelector class is deprecated since version 2.8 and will be removed in 3.0. Use directly the \Symfony\Component\CssSelector\CssSelectorConverter class instead: 1x
1x in ContentTest::testOuterHtml from Behat\Mink\Tests\Driver\Basic
```

@stof any news about this? I guess is Mink related.

I'll keep posting things here or in mink if while trying to fix the test i see something that actually needs fix in Mink and not in the Driver (it can happen).

**Comment by stof** [comment]
@jcalderonzumba Mink already fixed this usage of the deprecated class in its dev version. It will be released this weekend. Your Travis build sees it because it runs against the stable version of Mink

**Comment by stof** [comment]
@jcalderonzumba I suggest you to open a PR with your branch. It is easier to provide review comments on a PR than on a branch

**Comment by jcalderonzumba** [comment]
For this branch i'm working on?

**Comment by stof** [comment]
@jcalderonzumba yeah. We generally open PRs from branches in which we work, not for abandonned branches :smile: This allows commenting on the work being done.

Note that some of the test failures you have are related to the bug I'm fixing in https://github.com/jcalderonzumba/MinkPhantomJSDriver/pull/49

**Comment by jcalderonzumba** [comment]
I think this can be close, new mink driver test suite has been added.
