### ISSUE TITLE
The testsuite does not run on HHVM because it does not have the builtin webserver

### ISSUE THREAD

**Issue by stof** [jcalderonzumba/MinkPhantomJSDriver#40]
HHVM does not have a builtin webserver.

The trick we use in mink driver repos is to always start the webserver with PHP 5.6 (which is installed on Travis all the time, even if it is not the selected runtime). We don't really need the web fixtures to run on all PHP versions. We need the library code to use it. See https://github.com/minkphp/MinkSelenium2Driver/blob/1a527cc2de40a409b0997bf886dfd05068acfb18/.travis.yml#L33 for this setup

However, given that you don't start the webserver in the Travis configuration but in the test script itself, it is harder to handle it.

**Comment by jcalderonzumba** [comment]
Cool!!, I did not know that, will take a look. All this travis is fairly new to me.

**Comment by stof** [comment]
it might be simpler to configure the CI setup on Travis once it does not need to run both the driver testsuite and the behat extension tests at the same time. I suggest making the package split first.

**Comment by jcalderonzumba** [comment]
Yes, Package split to me is the highest priority and maybe while doing that I can try and fix the overwritten tests that you mentioned in the other issue.

**Comment by stof** [comment]
Well, this should be 2 separate tasks IMO. splitting the packages should be a matter of creating a new repo for the extension, extracting the code in it and then updating your own projects to add the dependency on the new package before cleaning the driver repo.

given the project is not yet advocated in the Mink documentation, it is unlikely to be used by lots of people outside yourselves (it only has 162 installs registered on Packagist from installers not disabling the stat reporting)

**Comment by jcalderonzumba** [comment]
After doing the splitting of Driver and Extension, i have upgraded the test script so it does the trick for the webfixtures, now the driver is "green" on all matrix.
Next step is to fix the javascript issue in the other issue still open and then it will be a real green test library.
