### ISSUE TITLE
Document if interacting with alert() and confirm() boxes is supported

### ISSUE THREAD

**Issue by tuxayo** [jcalderonzumba/MinkPhantomJSDriver#55]
I can't find on the Mink or this driver's doc if it's supported.
And even less how it works.

**Comment by jcalderonzumba** [comment]
@tuxayo As far as i remember i think those alert and confirm are monkeypatched in this driver so they do not "stop" testing steps.

**Comment by jcalderonzumba** [comment]
Closing and updating the documentation because phantomjs does not support alert handling directly but via http://phantomjs.org/api/webpage/handler/on-confirm.html.
