### ISSUE TITLE
Using fillField with values other than strings

### ISSUE THREAD

**Issue by thedamnedrhino** [jcalderonzumba/MinkPhantomJSDriver#57]
Using `fillField()` with values other than strings, e.g: ints, leads to pretty hard to trace error, I think the bundle should either implicitly handle that or throw a more informative `Exception`.

**Comment by jcalderonzumba** [comment]
@thedamnedrhino Can you put a simple code to reproduce and the output you get?.

**Comment by thedamnedrhino** [comment]
Yes, I'll do that in the coming days. From what I remember phantomjs tries to call `substr` on the passed value, but values of a type other than string don't implement that.

**Comment by jcalderonzumba** [comment]
I think i know where the problem is, i have to fix the setValue function of the Mink Driver interface is causing problem in other cases not only in yours.

**Comment by mglaman** [comment]
Just had this happen with ints. The code currently converts bool to string, see https://github.com/jcalderonzumba/MinkPhantomJSDriver/blob/9407a5c0504edf6efd84587aaacadd002e80f48e/src/FormManipulationTrait.php#L34

**Comment by jcalderonzumba** [comment]
@mglaman I have reviewed your code, looks ok but i made only one small change request

**Comment by jcalderonzumba** [comment]
Closing as it was solved in PR merged.
