### ISSUE TITLE
using the named content selector even looks in javascript String literals

### ISSUE THREAD

**Issue by thedamnedrhino** [jcalderonzumba/MinkPhantomJSDriver#58]
Finding elements with `find('named', ['content', 'some string'])` looks even in `<javascript>` tags, and returns those elements if it does find an equivalent String literal anywhere in there. I don't think this should happen.

**Comment by jcalderonzumba** [comment]
@thedamnedrhino This is a Mink issue more that the driver itself, Mink does some transformations before calling to MinkPhantomJSDriver to get the elements.

**Comment by jcalderonzumba** [comment]
@stof: Correct me if i'm wrong but is this an intended behaviour in the base classes of Mink? Should i fix something on my side or should i move this ticket to minkphp?

**Comment by stof** [comment]
Note that there is no ``<javascript>`` tag in HTML...

And yes, Mink currently does not try to exclude elements which are not displayed, like ``<script>``. Excluding them from the XPath query is not easy.

**Comment by stof** [comment]
hmm, thinking about it again, it might be easier than I thought. Please open an issue about it on Mink.

**Comment by jcalderonzumba** [comment]
Closing, will be handled here: https://github.com/minkphp/Mink/issues/728
