### ISSUE TITLE
One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration

### ISSUE THREAD

**Issue by kasik96** [jcalderonzumba/MinkPhantomJSDriver#63]
Hi, i still getting this error message when i try to ->visit second page like this:

>                      $driver = new Zumba\Mink\Driver\PhantomJSDriver('http://localhost:8510');
> 			$session = new Session($driver);
> 			$session->start();
> 
> 			sleep(2);
> 
> 			$session->visit('https://webadress.com/signin');
> 
> 			sleep(3);
> 
> 			$page = $session->getPage();
> 			$registerForm = $page->find('css', 'form:first-of-type');
> 			$page->find('css', 'input[name="user"]')->setValue($this->username);
> 			$page->find('css', 'input[name="password"]')->setValue($this->password);
> 			$registerForm->submit();
> 
> 			sleep(10);
> 
> 			$session->visit('https://webadress.com/upload'); //here it break
> 
> 			sleep(3);

![screen shot 2016-10-11 at 10 43 10](https://cloud.githubusercontent.com/assets/7235992/19264059/8cf14688-8f9f-11e6-9ee7-eb3d6f7ad0f4.png)

[gastonjs.log.zip](https://github.com/jcalderonzumba/MinkPhantomJSDriver/files/521309/gastonjs.log.zip)

**Comment by ganchclub** [comment]
you can turn errors off like this: 

$driver = new PhantomJSDriver('http://localhost:8510');
$driver->getBrowser()->jsErrors(false);

**Comment by kasik96** [comment]
Thanks 😊.

**Comment by bhargav3** [comment]
@ganchclub Just curious, is `sleep()` necessary?

**Comment by mmenozzi** [comment]
Hi guys, how to set jsErrors to false when using Behat?
Thank you.
