### ISSUE TITLE
Timeout after page loads

### ISSUE THREAD

**Issue by ganchclub** [jcalderonzumba/MinkPhantomJSDriver#64]
Is there a way on PHP side to set a timeout after page loads to let JavaScript finish loading additional resources?

**Comment by jcalderonzumba** [comment]
I don't think i fully understand the question, what do you want to do?. Tell the driver to "wait" until everything is loaded?

**Comment by ganchclub** [comment]
yes, that's what I meant, thanks.

**Comment by jcalderonzumba** [comment]
Ok, i get it.

One thing you should consider is that, one thing is for resources to be loaded (css, javascript, images) and another completely different is for the page to be "completely" ready to use.

If you are using javascript that does work after all is loaded you have no choice but to wait until those async scripts have finishing doing things on the backgroup, for phantomjs (not even for this driver) the page is "ready" once all is loaded.
