### ISSUE TITLE
reset() should not mark a driver "stopped"

### ISSUE THREAD

**Issue by dennisverspuij** [jcalderonzumba/MinkPhantomJSDriver#69]
$this->started is set to false in SessionTrait::reset(), while it should stay true according to [\Behat\Mink\Driver\DriverInterface](http://apigen.juzna.cz/doc/Behat/Mink/source-class-Behat.Mink.Driver.DriverInterface.html#76-96) method description.
Instead SessionTrait::stop() should set it to false after calling $this->reset().

**Comment by jcalderonzumba** [comment]
@dennisverspuij: Problem solved 👍

**Comment by dennisverspuij** [comment]
Awesome. Though now its only partially fixed because it should be set to false in stop() after calling $this->reset().

**Comment by jcalderonzumba** [comment]
@dennisverspuij You are definitely right, i missed that because since in stop() i was calling reset the started=false was done by reset. I'll fix it asap.
