### ISSUE TITLE
`Zumba\PhantomJSExtension` extension file or class could not be located.

### ISSUE THREAD

**Issue by ThomasLandauer** [jcalderonzumba/MinkPhantomJSDriver#75]
I'm using mink with behat, and when I'm starting behat, I get this error message:
``
`Zumba\PhantomJSExtension` extension file or class could not be located.
``

Hints:
* I installed it using composer as shown at https://github.com/jcalderonzumba/MinkPhantomJSDriver#installation--compatibility
* I'm new to PhantomJS. However, I'm getting some page when I open `http://127.0.0.1:8510/api` in the browser. So it looks like it's up and running :-)
* Are you sure that at https://github.com/jcalderonzumba/MinkPhantomJSDriver/blob/master/README.md#how-to-use the line `Zumba\PhantomJSExtension:` is correct? No `~` and no indendation on the next line?
* I haven't used this anywhere, since I figure I don't need it when using behat:
``
$driver = new Zumba\Mink\Driver\PhantomJSDriver('http://localhost:8510');
``
* Behat is working, when I switch back to selenium2

Thank you!

**Comment by jcalderonzumba** [comment]
If you want to use this driver with behat you need to modify your composer.json and add the following package.
https://github.com/jcalderonzumba/MinkPhantomJSExtension
you can check https://github.com/jcalderonzumba/MinkPhantomJSExtension/blob/master/behat.yml for an example of the behat.yml

**Comment by ThomasLandauer** [comment]
Thanks! I think this should be explained in readme.md!  
I'm closing this issue.
